### ISSUE TITLE
Issue in script & config

### ISSUE THREAD

**Issue by Orum** [stefonarch/lxqt-labwc-session#10]
I've found two separate issues in this project.  First is right [here](https://github.com/stefonarch/lxqt-labwc-session/blob/90111f391c9019ff25275b590af6357dd5629aef/startlxqtlabwc.in#L95) where you query for where labwc is, but then never store the result in `$LABWC_EXECUTABLE`.  I'm also not sure there is a reason to use `whereis` piped to `awk` when you can just use `which` instead.  In other words, I think that line should simply be:
```
LABWC_EXECUTABLE=`which labwc`
```

The second issue is [here](https://github.com/stefonarch/lxqt-labwc-session/blob/90111f391c9019ff25275b590af6357dd5629aef/config/labwc/autostart#L44) where the line should be commented out, but isn't.

**Comment by stefonarch** [comment]
I wasn't fully awake this morning when I committed the [change](https://github.com/stefonarch/lxqt-labwc-session/commit/90111f391c9019ff25275b590af6357dd5629aef`) to "whereis", thanks. I think I can assume "which" to be installed if people compile this.

Thanks!
