### ISSUE TITLE
Just ask a question for the environment variable

### ISSUE THREAD

**Issue by ffs-akl** [stefonarch/lxqt-labwc-session#11]
As I understanded, setting environment variables (e.g. LANG, QT_IM_MODULE) in the environment file of labwc  should have the same effect as setting it in startlxqtlabwc, but actually setting it in labwc doesn't seem to have any effect to the lxqt session.    I knew it's not an issue, just wanted to ask why. please help!

**Comment by stefonarch** [comment]
Actually there are 3 places which should work: `startlxqtlabwc`, labwc/environment and session settings → advanced. How do you set them in labwc/environment? This should work the same.

**Comment by ffs-akl** [comment]
Setting in startlxqtlabwc worked,  but in labwc/environment didn't work.

**Comment by ffs-akl** [comment]
I tried to set LANG in ~/.config/labwc/environment , and logged in labwc,  it only don't take effect on the menu of windows title.  So it is an issue of labwc

**Comment by stefonarch** [comment]
Check `echo $LANG` after login, lxqt will set that too, maybe overriding it.

**Comment by ffs-akl** [comment]
I checked the LANG with "echo $LANG",   It is set up correctly， but didn't take effect on the menu of windows title

**Comment by ffs-akl** [comment]
The above is a bit less detailed, so I'm going to go into more detail about the two variables LANG and QT_IM_MODULE.
for LANG,  set it in /etc/environment or startlxqtlabwc   can take effect on  all of menu（At this point, running the command echo $LANG reveals that it is set correctly）
                    set it in $HOME/.config/environment  didn't  only take effect on the menu of windows title.  Directly logging into labwc, it does the same thing.  （At this point, running the command echo $LANG reveals that it is set correctly）
              
for QT_IM_MODULE,    set it in /etc/environment or startlxqtlabwc   can take effect on all of QT applications  （At this point, running the command echo $QT_IM_MODULE  reveals that it is set correctly）
                                         set it in $HOME/.config/environment    can‘t take effect on  all of QT applications（At this point, running the command echo $QT_IM_MODULE  reveals that it isn't set ）

**Comment by stefonarch** [comment]
` $HOME/.config/environment` is not standard and will not be read afaik.  `$HOME/.config/labwc/environment` or just `export foo=xyz` in `~/.bashrc` or `~/.profile`.

**Comment by ffs-akl** [comment]
Sorry,  Type error,  $HOME/.config/environment  shall be $HOME/.config/labwc/environment.
At the time of my testing，I set it in $HOME/.config/labwc/environment， not in $HOME/.config/environment.

**Comment by ffs-akl** [comment]
> for QT_IM_MODULE, set it in /etc/environment or startlxqtlabwc can take effect on all of QT applications （At this point, running the command echo $QT_IM_MODULE reveals that it is set correctly）
> set it in $HOME/.config/labwc/environment can‘t take effect on all of QT applications（At this point, running the command echo $QT_IM_MODULE reveals that it isn't set ）

I just tried again,  setting in $HOME/.config/labwc/environment  have the same effect as setting in /etc/environment or startlxqtlabwc

for LANG,  that is an issue of labwc
<img width="645" alt="批注+2024-06-13+111226" src="https://github.com/stefonarch/lxqt-labwc-session/assets/166389780/6c726654-1f70-47bd-a2f2-fba3691024aa">
