### ISSUE TITLE
window rules for pcmanfm-qt --desktop

### ISSUE THREAD

**Issue by johanmalm** [stefonarch/lxqt-labwc-session#2]
https://github.com/stefonarch/lxqt-labwc-session/blob/4a94dbc4944b5724b640e843fd125995e061b385/config/labwc/rc.xml#L100

I think it would be better not to Maximize here but use these two instead:

```xml
      <action name="MoveTo" x="0" y="0"/>
      <action name="ToggleKeybinds"/>
```

**Comment by stefonarch** [comment]
I see, I thought it was impossible to close the desktop by shortcut but it was possible. Thanks!

**Comment by stefonarch** [comment]
Testing I see 2 new issues now:
* waybar is covered by the desktop as it is on the bottom layer 
https://github.com/stefonarch/lxqt-labwc-session/blob/d8d4e7a079d7a53cdd4579941b95b5ac09c1e185/config/waybar/taskbar.config#L2
* with focus on the desktop no shortcut is working anymore, like desktop switch or open apps

Reverting rules for the moment to
```
      <action name="ToggleAlwaysOnBottom"/>
      <action name="Maximize"/>
```

**Comment by stefonarch** [comment]
https://github.com/lxqt/pcmanfm-qt/issues/1871
Users should compile and use this.
