### ISSUE TITLE
AUR build fails

### ISSUE THREAD

**Issue by johanmalm** [stefonarch/lxqt-labwc-session#3]
I get the following when trying to build the AUR package.
Looks like we need some xdg package. Apologies, not investigated further.

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find XdgUserDirs (missing: XdgUserDirsUpdate_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/lxqt-build-tools/find-modules/FindXdgUserDirs.cmake:49 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by stefonarch** [comment]
Looks that line isn't necessary and only a leftover from the original CMake.txt.
Please test again.

**Comment by redtide** [comment]
@stefonarch I guess `xdg-user-dirs-update` should be needed for a XDG based desktop anyway, isn't it?

**Comment by redtide** [comment]
Looks a bit strange to me that [xdg-user-dirs-update](https://github.com/lxqt/lxqt-build-tools/blob/master/cmake/find-modules/FindXdgUserDirs.cmake#L45) is not installed already with LXQt, so I wonder if it should be added as dependency?

**Comment by stefonarch** [comment]
On arch it's a dependency of [lxqt-session](https://archlinux.org/packages/extra/x86_64/lxqt-session/), so here it hasn't to be listed.
