### ISSUE TITLE
Keymap import fails if not quoted in lxqt settings

### ISSUE THREAD

**Issue by cg9999** [stefonarch/lxqt-labwc-session#6]
If the keymap layout value is not enclosed in double quotes, the lxqt-settingsexporter produces invalid line

for example this 
```
[Keyboard]
layout=fi
model=pc105
variant=
```

becomes this:

`XKB_DEFAULT_LAYOUT=layout=fi`

This causes labwc to crash in wlroots

```
#0  xkb_keymap_ref (keymap=keymap@entry=0x0) at ../libxkbcommon/src/keymap.c:61
#1  0x00007f206a71e169 in wlr_keyboard_set_keymap (kb=0x55a0369683a8, keymap=0x0) at ../wlroots-0.16.2/types/wlr_keyboard.c:174
```
replacing the sed invocation in lxqt-settingsexporter with something like
`sed 's/[^=]*="*\([^"]*\)"*/\1/'`
fixes the issue for me

**Comment by stefonarch** [comment]
I see, should be fixed now, thanks!
