### ISSUE TITLE
More portable

### ISSUE THREAD

**Issue by isf63** [stefonarch/lxqt-labwc-session#9]
https://github.com/stefonarch/lxqt-labwc-session/blob/5fceab129d581c2dcc5c8b5f228e14242e9d4220/startlxqtlabwc.in#L95 uses `which` which I had to install separately or the session failed. `whereis labwc | awk '{print $2}'` is more portable on typical distros (`base` on Arch brings in awk and whereis).

**Comment by stefonarch** [comment]
Thanks!
Saw it `which` is in  `base-devel` though.

**Comment by stefonarch** [comment]
I applied the change badly and reverted it. I don't understand why you didn't have which: https://archlinux.org/packages/core/any/base-devel/

There is another issue with it, as in my case:

```
$ whereis labwc | awk '{print $2}'
/usr/bin/labwc
$ which labwc
/usr/local/bin/labwc
```

**Comment by isf63** [comment]
I don't have `base-devel` installed although I probably should in the future.

> $ which labwc
> /usr/local/bin/labwc

Looks like `which` is the right tool then, looks like it is included by default on Debian/Ubuntu too. Not a big issue.
